# Narayana LRA client coordinator URL
# Override with env var: LRA_COORDINATOR_URL
lra.coordinator.url=http://localhost:8070/lra-coordinator

# Base URLs for downstream services
withdrawal.service.url=http://localhost:9082/withdrawal
deposit.service.url=http://localhost:9081/deposit
